In [60]:
import numpy as np


A = np.array([[11, 22, 33], [44, 55, 66],[77, 88, 99]])


print (A)

[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [61]:
# find median for each row
med = np.median(A,axis=1)
print (med)

[22. 55. 88.]


In [62]:
#make medians ino array
medA = np.outer(med, np.ones(3))

print(medA)

[[22. 22. 22.]
 [55. 55. 55.]
 [88. 88. 88.]]


In [63]:
#Subracting medians from each line
A_med_sub = np.subtract(A,medA)

print (A_med_sub)

[[-11.   0.  11.]
 [-11.   0.  11.]
 [-11.   0.  11.]]


In [66]:

np.cbrt(A_med_sub)

array([[-2.22398009,  0.        ,  2.22398009],
       [-2.22398009,  0.        ,  2.22398009],
       [-2.22398009,  0.        ,  2.22398009]])

In [ ]:
#Subtracting using for loop

In [77]:
B = np.array([[1,2,3], [3,4,5]])

for row in B:
    for i in row:
        
    print (row)
    

[0 1 2]
[2 3 4]
