In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
a = np.array([[5,9,2],[4,1,9], [7,6,2]])
print (a)

[[5 9 2]
 [4 1 9]
 [7 6 2]]


In [3]:
med = np.median(a, axis=1)
print (med)

[5. 4. 6.]


In [4]:
medians_expanded = np.outer(med, np.ones(3))
print(medians_expanded)

[[5. 5. 5.]
 [4. 4. 4.]
 [6. 6. 6.]]


In [5]:
v1_a = np.subtract(a, medians_expanded)
print(v1_a)

[[ 0.  4. -3.]
 [ 0. -3.  5.]
 [ 1.  0. -4.]]


In [7]:
## my black point will be -1
v2_a = np.subtract( v1_a, -1 )
print(v2_a)


[[ 1.  5. -2.]
 [ 1. -2.  6.]
 [ 2.  1. -3.]]


In [8]:
v3_a = np.cbrt(v2_a)
print(v3_a)

[[ 1.          1.70997595 -1.25992105]
 [ 1.         -1.25992105  1.81712059]
 [ 1.25992105  1.         -1.44224957]]


In [9]:
v3_L = v3_a.flatten()
print(v3_L)

[ 1.          1.70997595 -1.25992105  1.         -1.25992105  1.81712059
  1.25992105  1.         -1.44224957]


In [10]:
np.sort(v3_L) 

array([-1.44224957, -1.25992105, -1.25992105,  1.        ,  1.        ,
        1.        ,  1.25992105,  1.70997595,  1.81712059])

In [11]:
range(0,256,1) 

range(0, 256)

In [12]:
np.interp(v3_L, (v3_L.min(), v3_L.max()), (0, 256))

array([191.82107545, 247.58456142,  14.32058922, 191.82107545,
        14.32058922, 256.        , 212.2359978 , 191.82107545,
         0.        ])